beta2beta.settings:
  type: config_object
  label: 'Beta2Beta settings'
  mapping:
    version:
      type: integer
      label: 'Force beta version'
    forced_update:
      type: boolean
      label: 'Indicates a forced beta version has been set'
