name: Cohesion website settings
type: module
description: 'Defines the website settings configuration entities.'
core: 8.x
package: cohesion
libraries:
  - core/jquery.ui
  - core/jquery.ui.animate
dependencies:
  - cohesion