# Website settings
administer website settings:
  title: Cohesion Website settings
  description: 'Grant access to administer Cohesion website settings.'

# Website settings
access color_picker:
  title: Cohesion Color picker
  description: 'Grant access to the color picker. Restricted access will only allow the use of the color palette.'
