language: php

services:
  - mysql

before_install:
  - mysql -e 'CREATE USER "webadmin"@"%" IDENTIFIED BY "webadmin"; create database drupal; GRANT ALL ON drupal.* TO "webadmin"@"%";'
  - COMPOSER_MEMORY_LIMIT=-1 composer create-project acquia/lightning-project:8.7.1 drupal --no-install
  - cd $TRAVIS_BUILD_DIR/drupal && COMPOSER_MEMORY_LIMIT=-1 composer require acquia/lightning:4.1.0
  - cd $TRAVIS_BUILD_DIR/drupal && COMPOSER_MEMORY_LIMIT=-1 composer require drush/drush

install:
  - composer clearcache
  - cd $TRAVIS_BUILD_DIR && rsync -av . ./drupal/docroot/modules/contrib/cohesion --exclude drupal
  - cd $TRAVIS_BUILD_DIR/drupal && cat ./docroot/modules/contrib/cohesion/composer.json | jq -r '.require | to_entries[] | "\(.key):\(.value)"' | grep 'drupal/' | xargs -L 1 composer require --no-update --no-scripts -n
  - cd $TRAVIS_BUILD_DIR/drupal && cat ./docroot/modules/contrib/cohesion/composer.json | jq -r '."require-dev" | to_entries[] | "\(.key):\(.value)"' | xargs -L 1 composer require --no-update --no-scripts -n
  - cd $TRAVIS_BUILD_DIR/drupal && cat ./docroot/modules/contrib/cohesion/composer.json | jq -r '.suggest | to_entries[] | "\(.key)"' | grep 'drupal/' | xargs -L 1 composer require --no-update --no-scripts -n
  - cd $TRAVIS_BUILD_DIR/drupal && COMPOSER_MEMORY_LIMIT=-1 composer update --with-all-dependencies -n
  - cd $TRAVIS_BUILD_DIR/drupal && ./vendor/bin/drush si lightning --account-name=webadmin --account-pass=webadmin --db-url=mysql://webadmin:webadmin@127.0.0.1/drupal --site-name=Lightning -y
  - cd $TRAVIS_BUILD_DIR/drupal && ./vendor/bin/drush en -y cohesion

script:
  - cd $TRAVIS_BUILD_DIR/drupal && SYMFONY_DEPRECATIONS_HELPER=weak ./vendor/bin/phpunit -c ./docroot/core/phpunit.xml.dist --testsuite=unit --group Cohesion

cache: false

notifications:
  slack:
    secure: 3Gd4knmcC3LCg4ATELsl+4MHD77t/Vsw/T5CesFBckwGIEU9PN7AM0ToKbVwNx9MltXqIhtzk+wCmVrg6+GH7itlSPy+dhQlH37ML0RxUrD9dVj2hE2EGl6jY+RWuAOtcCQirgBjCgnHzFxUuovPNq06YB1mQh33qv6+S54C/v5jsJYTXFQYD+ihimkn+k7WhL4QlSmHFej2Y9O0mHB6aj8+E5vbeT7SRRNJ/x+JajIViqvQz3HDmW3XoUFS7SPuYXpSLHKuiLOxGMKEx7jbPh1Q+jflGDnQGzgH83dq0a17iUxNeCg2uyt6xRqcBTjHv7eIX2uC6ZVZbqFGG77AXRST8HnchdixYoR85jMI3Heyi7Pnhc/KZUnv+TyeAqbTzIByYvUaNAZcw/liIuLrN631GSjoOVm8hVzQ7FR3r0+fyWf3G+oUZxR/tUYtnn/BfYdVq5KmfN9Vc9m+cFSrXsKTCKrBaIcF6JIsbU2UH6NPDgSjNKPkivjwlLnA8PIQNRzI3B6Qvl2qFlP1LFReh5JrRMDd8qZ2ueyCnm5aMxkT33hdVKlYmqx5EeGd8dDxCmwJ9yA5IE9qeeQNereNMo67hyiON9rG3KOJILOFVXuCfUorxoI2dy/XsdvxSe15DitMlHMejHbAIGSmAK5X32u/J2krC+84FRR/opNFeYg=
