cohesion_template:
  type: cohesion_config_entity
  label: 'Cohesion template base'
  mapping:
    custom:
      type: bool
      label: 'Custom'
    twig_template:
      type: path
      label: 'Twig template filename'
